services:
  app:
    build:
      dockerfile: Dockerfile
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    container_name: ocr-app
    ports:
      - "${PORT_NUMBER}:${PORT_NUMBER}"
    env_file:
      - .env
    command: python3 main.py
